"""add_item_store_id
Revision ID: b135ed17a7e2
Revises: b7409b94482f
Create Date: 2026-07-03 14:04:11.065688
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = 'b135ed17a7e2'
down_revision = 'b7409b94482f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('item_store_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'item_store_id')
    # ### end Alembic commands ###
