"""add_sales_column
Revision ID: b7409b94482f
Revises: b086d3957d80
Create Date: 2026-07-03 13:51:58.422329
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = 'b7409b94482f'
down_revision = 'b086d3957d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sales', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'sales')
    # ### end Alembic commands ###
